---

- name: conditionally include secret vars from either gitignored vars_secret.yml or encrypted vars_vault.yml
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - vars_secret.yml
        - vars_vault.yml
      paths:
        - 'vars'
      skip: false  # if true will skip task if no var file found

- name: assert password vars not left empty
  ansible.builtin.assert:
    that:
      - postgres_admin_pass != ""
      - app_database_pass != ""
